apiVersion: v1
kind: Service
metadata:
  name: model-deploy-service
spec:
  selector:
    app: model-deploy
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deploy
spec:
  selector:
    matchLabels:
      app: model-deploy
  replicas: 4
  template:
    metadata:
      labels:
        app: model-deploy
    spec:
      containers:
      - name: model-deploy
        image: model-deploy
        imagePullPolicy: Never
        ports:
        - containerPort: 5000